### ISSUE TITLE
Peer to Peer code review 

### ISSUE THREAD

**Issue by MeqdamAlqudah** [zemola/Leaderboard#5]
Great Work AZEEM 👍 
but I have highlights on your project.
1- Your UI is cool but It is close to the Microverse version I think it would be better if you make some changes.
2- I noticed that the name and the score have no limits in the project.
![image](https://user-images.githubusercontent.com/74744787/147328520-261b5658-78c3-47fd-b392-bda6275dbfd2.png)
3-there is no functionality to deal with empty name and score inputs the user receives errors.
![image](https://user-images.githubusercontent.com/74744787/147328638-dc390adc-18d5-48b7-93c7-a41f127ecf50.png)

4- It would be better to sort the items in the list 
![image](https://user-images.githubusercontent.com/74744787/147328757-6d9b54fd-768c-4b15-a466-0b8bb94cb191.png)

💯 Thank you for being the presenter today Azeem I wish you all good luck 💯

**Comment by zemola** [comment]
@MeqdamAlqudah 

Thank you for your review.

**Comment by zemola** [comment]
Resolved
